language: r

r_binary_packages:
  - rgdal
  
r_github_packages:
  - jimhester/robustr
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: Y7ly6rxiG4EBAKKREFovZ1LPQp2ghrN7ThIfkMaQ1XCQLRV0D39a3Uuf1UigS6gpqrtaedXakbtZwG3CIhICILRRiQSZch3gGZUNMRkVrG/0wZDn7HwWOquTxPJEeH1AUlKYToxiI6rRqd/c3U4FwisKuIUHmvqDRA1NEtdiqJY=
